### PR TITLE
Fixup/harmonize linter and prettier rules

### PR DESCRIPTION
**Pull request by klondikemarlen**
Normalize the "web" package eslint config to include prettier settings.
Add a basic prettier/eslint setup to the "api" package.

**NOTE: Should be merged after https://github.com/icefoganalytics/asset-apps/pull/18 to avoid conflicts to that more important PR**

Normalize code in "web" and "api" via.
In web:
`npm run lint`
in app:
`npm run lint`

## Testing instructions
Boot the app
- `dev up`
- `cd api; npm run start`
- `cd web; npm run start`

Check that the app boots and that pages through no new errors.

### CODE REVIEW

**Comment by datajohnson** [comment]
@klondikemarlen This PR appears to have 7 files in conflict... I think I merged in the right order this time, but can you double-check. Sorry!

**Comment by klondikemarlen** [comment]
> @klondikemarlen This PR appears to have 7 files in conflict... I think I merged in the right order this time, but can you double-check. Sorry!

No worries! I expected some merge conflicts, and prefer fixing them here :)

**Comment by klondikemarlen** [comment]
@datajohnson I rebased and fixed up the conflicting commits.

**Comment by klondikemarlen** [comment]
@datajohnson Did you mean to close this or merge it?

**Pull request closed without merging**
