### PR TITLE
Issue 8: Finish Wiring Tag Request on Dashboard

### LINKED ISSUE #8: Finish wiring up Tag Request on /dashboard
Needs to generate unique 'YXXXXXX' numbers for the tag, record the owner, insert row(s) into `tblTestTagRepeat`. The format of that table is CRAP but it's legacy and currently hooked up to the printer, so we can't change it. Not all fields are required in there, but 

 - YTG_NUMBER
 - Mailcode

are the big ones and fill in any other we have data for based on the request.

It should then email someone (likely Rob, but I'll get that figured out and into the .env.sample)

We will give the requestor access to come back and add the metadata similar to the hard-coded current workflow. We will email a link (`/asset-tags/recent`) to the requestor that shows them the newly generated 'YXXXXXX' numbers.

### PR DESCRIPTION
**Pull request by klondikemarlen**
Fixes #8.

## Context

Wire front-end "asset tag request" workflow to back-end API.
A "tag request" generates an `asset_item` for each tag requested, and an entry in the "asset tag printer table" (a.k.a. `tblTestTagRepeat`)
Add a `y_numbers` sequence that increments when a the new `asset_item` is created.
> I made a lot of guess about what data was needed for what tables. A second opinion would be appreciated.
> Information such as "purchase price" might need to be included.

## Deployment Instructions
I needed to create a new sequence for generation Y numbers. I did this by dumping the current Y numbers to a file and finding the maximum value.
```bash
# dump tags to a CSV file via bash
/opt/mssql-tools/bin/sqlcmd \
  -U sa \
  -P Testing1122 \
  -H localhost \
  -d AssetControl \
  -Q \"select [tag] from asset_item\" -W -w 999 -s\",\" -o /tmp/y-tags.csv

# in development this can be done via the following
dev sqlcmd -Q \"select [tag] from asset_item\" -W -w 999 -s\",\" -o /tmp/y-tags.csv
container_name="db"
container_id=$(docker ps -aqf "name=$container_name")
docker cp $container_id:/tmp/y-tags.txt ~/Downloads/y-tags.txt
```
I then extracted the maximum tag with some handy ruby code (though if the dataset is large, Python would be much faster):
```ruby
require 'csv'

y_tags_path = File.expand_path('~/Downloads/y-tags.csv')
y_tags = CSV.read(y_tags_path, headers: true)

y_tag_numbers = y_tags.map { |row|
  tag = row['tag']
  number_match = /([0-9]+)/.match(tag)
  next if number_match.nil?

  number_match[0]
}.compact.map(&:to_i).uniq

highest_tag_number = y_tag_numbers.max
# 80015048
```
After that I added the sequence to the database via:
```sql
CREATE SEQUENCE dbo.y_numbers AS int START WITH 80015049 INCREMENT BY 1;
GO
```

## Refactors
1. Renamed /api/asset-item/ querying route to /api/asset-item/query to make room for the standard CRUD creation pattern of a POST to a resource endpoint creating a resource of that type.
2. Drop "TAG_URL" front-end url helper as it is a duplicate of "ASSET_URL"

## Enhancements
Made use of a wrapper around "axios" that in the future can be used for standardized notifications at an application level or for standardized query and parameter parsing/serialization.
Improved dev tooling, app can now be booted vai `bin/dev boot`.
TODO: update README.md to reference new dev tooling.

## Screenshots
image

### CODE REVIEW

**Comment by datajohnson** [comment]
Keeping this... the Y numbers in production had all sorts of crap characters.

```
select tag, CAST(SUBSTRING(tag, 2, 15) as int) from asset_item
where tag  like 'Y%' and tag not like 'YTT' and tag not like 'YG%' and tag not like '%E'
and tag not like '%A' and tag not like '%P' and tag not like '%?'and tag not like '%.'
and tag not like '%TC' and tag not like '%-%'and tag not like '%B' and tag not like '%F%'
and tag not like '%U%' and tag not like '%C' and tag not like '%H' and tag not like '%D'
and tag not like '%T'
order by 2 desc

CREATE SEQUENCE dbo.y_numbers AS int START WITH 2355016 INCREMENT BY 1;
```

**Comment by klondikemarlen** [comment]
Interesting ... I think I misunderstood what was considered that max. I didn't realized the valid format was that specific. I just found the highest consecutive string of numbers.

**Comment by datajohnson** [comment]
No, your solution was technically correct, I just saw the number it came up with and knew it wasn't in the ballpark of the numbers Rob has printed recently. So I iteratively wrote the most gross query of all time ;)

**Comment by datajohnson** [comment]
Additionally, I think we should change the way the MAX_DATE works... for me in certain setups (and I can't predict how the production setup is), I get a timezone error where it things it's the year 10,000 and the database insert fails. It's a STUPID field. Let's just set it to the year 2099 instead of 9999. At some point, maybe we can refactor the tag printing table and printer setup to work better.

**Comment by klondikemarlen** [comment]
Yeah it felt very unstable; that's why I made it a constant.
I think there was something else I wanted to fix too so I'll toss up a fixup PR

**Pull request merged**
